# This is a basic workflow to generate and deploy the documentions.

name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: julia-actions/setup-julia@latest
      
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      
      - name: Build and deploy
        run: julia --project=docs/ docs/make.jl
